name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Install
        run: yarn
      - name: Start
        run: "yarn presnapshots"
      - name: Percy Test
        uses: percy/exec-action@v0.1.1
        with:
          command: "yarn snapshots"
        env:
          PERCY_TOKEN: a563b7b7da58c3dc58e124e81cf5e8ac484db9ef4397d004053bbc6d776f2a40
